src/Amicale/AccueilBundle/Form/Entity/Produit.php
<?php

namespace Amicale\AccueilBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Amicale\AccueilBundle\Entity\Produit
 *
 * @ORM\Entity(repositoryClass="Amicale\AccueilBundle\Entity\ProduitRepository")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="produit")
 */
class Produit {

    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $titre
     * @ORM\Column(name="titre", type="string", length=255)
     */
    private $titre;

    /**
     * @var string $marque
     * @ORM\Column(name="marque", type="string", length=50, nullable=true)
     */
    private $marque;

    /**
     * @var text $contenu
     * @ORM\Column(name="contenu", type="text", nullable=true)
     */
    private $contenu;

    /**
     * @var integer $prix
     * @ORM\Column(name="prix", type="integer", nullable=true)
     */
    private $prix;
    
    /**
     * @var string $typeProduit
     * @ORM\ManyToOne(targetEntity="Amicale\AccueilBundle\Entity\TypeProduit")
     * @ORM\JoinColumn(nullable=false)
     */
    private $typeProduit;

    /**
     * @ORM\OneToOne(targetEntity="Amicale\AccueilBundle\Entity\Photo", cascade={"persist", "remove"})
     */
    private $photo;

    /**
     * @var datetime $createdAt
     * @ORM\Column(name="createdAt", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @var datetime $updatedAt
     * @ORM\Column(name="updatedAt", type="datetime", nullable=false)
     */
    private $updatedAt;
    
    /**
     * Now we tell doctrine that before we persist or update we call the updatedTimestamps() function.
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function prePersist(){
        $this->updatedTimestamps();
    }
        
    public function updatedTimestamps()
    {
        $this->setUpdatedAt(new \DateTime());

        if($this->getCreatedAt() == null)
        {
            $this->setCreatedAt(new \DateTime());
        }
    }


    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function getTitre() {
        return $this->titre;
    }

    public function setTitre($titre) {
        $this->titre = $titre;
    }

    public function getMarque() {
        return $this->marque;
    }

    public function setMarque($marque) {
        $this->marque = $marque;
    }

    public function getContenu() {
        return $this->contenu;
    }

    public function setContenu($contenu) {
        $this->contenu = $contenu;
    }

    public function getPrix() {
        return $this->prix;
    }

    public function setPrix($prix) {
        $this->prix = $prix;
    }

    /**
     * Get typeProduit
     *
     * @return Amicale\AccueilBundle\Entity\TypeProduit
     */
    public function getTypeProduit() {
        return $this->typeProduit;
    }
    
    /**
     * Set typeProduit
     *
     * @param Amicale\AccueilBundle\Entity\TypeProduit $typeProduit
     */
    public function setTypeProduit(\Amicale\AccueilBundle\Entity\TypeProduit $typeProduit) {
        $this->typeProduit = $typeProduit;
    }

    /**
     * @return Amicale\AccueilBundle\Entity\Photo
     */
    public function getPhoto() {
        return $this->photo;
    }
    
    /**
     * @return path photo
     */
    public function getPhotoPath() {
        if(!$this->photo){
            return 'uploads/img/divers.png';
        }
        return $this->photo->getWebPath();
    }
    
    /**
     * @return path photo
     */
    public function getPhotoAlt() {
        if(!$this->photo){
            return 'divers.png';
        }
        return $this->photo->getAlt();
    }

    /**
     * @param Amicale\AccueilBundle\Entity\Photo $photo
     */
    public function setPhoto(\Amicale\AccueilBundle\Entity\Photo $photo = null) {
        $this->photo = $photo;
    }

    public function getCreatedAt() {
        return $this->createdAt;
    }

    public function getUpdatedAt() {
        return $this->updatedAt;
    }
    
    public function setCreatedAt($createdAt) {
        $this->createdAt = $createdAt;
    }

    public function setUpdatedAt($updatedAt) {
        $this->updatedAt = $updatedAt;
    }


}

?>

src/Amicale/AccueilBundle/Controller/AccueilController.php
<?php

namespace Amicale\AccueilBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class AccueilController extends Controller {

    public function indexAction() {
        $response = new Response();
        $response->setSharedMaxAge(300); # en secondes, donc environ 10 minutes
        $response->setPublic();        
        $response->setMaxAge(300);
        // Check that the Response is not modified for the given Request
        if (!$response->isNotModified($this->getRequest())) {
            // return the 304 Response immediately
            $em = $this->getDoctrine()->getManager();
            $repository = $em->getRepository('AmicaleAccueilBundle:Produit');
            $produits = $repository->getLastRecents(5);
            $date = new \DateTime();
            $response->setLastModified($date);
            $response->setContent($this->render('AmicaleAccueilBundle:Accueil:index.html.twig', array('produits' => $produits)));       
        }

        return $response;
    }

}

src/Amicale/AccueilBundle/Resources/views/Accueil/index.html.twig
{% extends "AmicaleAccueilBundle::layout.html.twig" %}

{% block title %}
    {{ parent() }} - Accueil
{% endblock %}


{% block stylesheets %}
    {{ parent() }}
    {% stylesheets '@AmicaleAccueilBundle/Resources/public/css/frontend/*' %}
<link href="{{ asset_url }}" type="text/css" rel="stylesheet" />
    {% endstylesheets %}
{% endblock %}

{% block amicaleaccueil_body %}
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span10">
            <div id="carousel">
                    <div id="myCarousel" class="carousel slide">
                        <div class="carousel-inner thumbnail">
                        {% for produit in produits %}
                            {% if loop.first %}
                            <div class="item active"> 
                                <img src="{{ asset(produit.photoPath) }}" alt="{{ produit.photoAlt }}" />
                                <div class="carousel-caption">
                                    <p>{{ produit.titre }}</p>
                                </div>
                            </div>
                            {% else %}
                            <div class="item"> 
                                <img src="{{ asset(produit.photoPath) }}" alt="{{ produit.photoAlt }}" />
                                <div class="carousel-caption">
                                    <p>{{ produit.titre }}</p>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                        </div>
                          
                        <a class="carousel-control left" data-slide="prev" href="#myCarousel">‹</a>
                        <a class="carousel-control right" data-slide="next" href="#myCarousel">›</a>
                    </div>
                </div>
            <div id="presentation">
                <p>Bonjour à tous,</p>
                <p>Vous voici sur le site de l'Amicale du personnel de l'hopital Charles Perrens.</p>
                <p>Vous y trouverez tous nos nouveaux produits ainsi que les différentes expositions, offres de nos partenaires et actualités diverses.</p>
                <p>Vous avez également la possibilité, si vous êtes connecté, de passer vos commandes sur ce site et vous serez alerté dès sa réception.</p>
            </div>
        </div>           


        <div class="span2">
        </div>


        </div>
    </div>
{% endblock %}